config/routes.rb
Rails.application.routes.draw do

  root 'welcome#dashboard'
  resources :members
  devise_for :admins
  #devise_for :users
  resources :users
  resources :customers
  resources :orders
  resources :products
  resources :creditors
  resources :tokens, :only => [:create]
  put '/creditors/:id/paid' => 'creditors#paid_credits', :as => 'paid_credits'
  put '/orders/:id/paid' => 'orders#paid_company', :as => 'paid_company'
  put '/orders/:id/return' => 'orders#company_return', :as => 'company_return'
  get '/orders/admin-edit/:id' => 'orders#admin_edit', :as => 'admin_edit'
  get '/order/new/' => 'orders#admin_new', :as => 'admin_new'
  get '/notify' => 'welcome#notify', :as => 'notify'
  get '/test' => 'welcome#test', :as => 'test'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'orders/add_order'

end

app/controllers/creditors_controller.rb
class CreditorsController < ApplicationController
  before_action :set_creditors, only: [:show, :edit, :update, :destroy]
  # layout false
  # GET /members
  def index
    @page_title = 'All Creditors'
    @creditors = Credit.all
    @total_credits = @creditors.where(status: "Unpaid").sum(:amount)
  end

  # GET /members/1
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  def create
    @member = Member.new(member_params)

    if @member.save
      Admin.create(email: @member.email, password: "11111111", user_type: "members", member_id: @member.id)
      redirect_to members_path, notice: 'Member was successfully created.'
    else
      redirect_to new_user_path, notice: 'Form must be completed.'
    end
  end

  # PATCH/PUT /members/1
  def update
    if @creditors.update(status: "Paid")
      @creditors.order.update(status: "Paid")
      redirect_to creditors_path, notice: 'Member was successfully updated.'
    else
      redirect_to creditors_path, notice: 'Failed'
    end
  end

  # DELETE /members/1
  def destroy
    @member.destroy
    redirect_to members_url, notice: 'Member was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_creditors
      @creditors = Credit.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def member_params
      params.require(:member).permit(:name, :email, :job_rate, :time_rate, :day_rate, :night_rate, :time_cost, :day_cost, :night_cost, :fixed_rate)
    end
end

app/views/creditors/index.html.erb


<% content_for :breadcrumb do %>
    <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
      <li class="m-nav__item m-nav__item--home">
        <a href="#" class="m-nav__link m-nav__link--icon">
          <i class="m-nav__link-icon la la-home"></i>
        </a>
      </li>
      <li class="m-nav__separator">
        -
      </li>
      <li class="m-nav__item">
        <a href="/" class="m-nav__link">
											<span class="m-nav__link-text">
												Dashboard
											</span>
        </a>
      </li>
      <li class="m-nav__separator">
        -
      </li>
      <li class="m-nav__item">
        <a href="" class="m-nav__link">
											<span class="m-nav__link-text">
												Creditors
											</span>
        </a>
      </li>

    </ul>
<% end %>


<div class="row">
  <div class="col-xl-12">
    <!--begin:: Widgets/Quick Stats-->
    <div class="row m-row">
      <div class="col-sm-12 col-md-12 col-lg-12">
        <div class="m-portlet m-portlet--half-height m-portlet--border-bottom-brand  m-portlet--rounded">
          <div class="m-portlet__body">
            <div class="m-widget26">
              <div class="m-widget26__number">
                $<%= @total_credits %>
                <small>
                  Total Credits
                </small>
              </div>
              <div class="m-widget26__chart" style="height:90px; width: 220px;">
                <canvas id="m_chart_quick_stats_1"></canvas>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>
    <!--end:: Widgets/Quick Stats-->
  </div>
</div>
<div class="m-content">
  <div class="row">
    <div class="col-xl-12">
      <!--begin:: Widgets/Application Sales-->
      <div class="m-portlet m-portlet--full-height  m-portlet--rounded">
        <div class="m-portlet__head">
          <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
              <h3 class="m-portlet__head-text">
                All Creditors
              </h3>
            </div>
          </div>
        </div>
        <div class="m-portlet__body">
          <div class="tab-content">
            <div class="tab-pane active" id="m_widget11_tab1_content">
              <!--begin::Widget 11-->
              <div class="m-widget11">
                <div class="table-responsive">
                  <!--begin::Table-->
                  <table class="table">
                    <!--begin::Thead-->
                    <thead>
                    <tr>
                      <td>
                        Order #
                      </td>
                      <td>
                        User Name
                      </td>
                      <td>
                        Customer Name
                      </td>
                      <td>
                        Job Type
                      </td>
                      <td>
                        Amount
                      </td>
                      <td>
                        Status
                      </td>

                      <td class="m-widget11__total m--align-right">

                      </td>
                    </tr>
                    </thead>
                    <!--end::Thead-->
                    <!--begin::Tbody-->
                    <tbody>
                    <tr>
                      <% @creditors.each do |user| %>
                          <td>
                            <%= link_to admin_edit_path(user.order_id) do %>
                                <%= user.order_id %>
                            <% end %>
                          </td>
                          <td>
                            <%= user.order.get_user_name %>
                          </td>
                          <td>
          																		<span class="m-widget11__title">
          																			<%= user.name %>
          																		</span>
                          </td>
                          <td>
                            <%= user.order.get_actual_type %>
                          </td>
                          <td>
                            <%= user.amount %>
                          </td>
                          <td>
                            <%= user.status %>
                          </td>


                          <td class="m--align-right m--font-brand">
                            <% unless user.status == "Paid" %>
                                <%= link_to 'Paid', creditor_path(user.id), method: :put %>
                            
                            <% end %>
                          </td>
                          </tr>
                      <% end %>
                      </tbody>
                    <!--end::Tbody-->
                  </table>
                  <!--end::Table-->
                </div>

              </div>
              <!--end::Widget 11-->
            </div>
            <div class="tab-pane" id="m_widget11_tab2_content">
              <!--begin::Widget 11-->
              <div class="m-widget11">
                <div class="table-responsive">
                  <!--begin::Table-->
                  <table class="table">
                    <!--begin::Thead-->
                    <thead>
                    <tr>
                      <td class="m-widget11__label">
                        #
                      </td>
                      <td class="m-widget11__app">
                        Application
                      </td>
                      <td class="m-widget11__sales">
                        Sales
                      </td>
                      <td class="m-widget11__change">
                        Change
                      </td>
                      <td class="m-widget11__price">
                        Avg Price
                      </td>
                      <td class="m-widget11__total m--align-right">
                        Total
                      </td>
                    </tr>
                    </thead>
                    <!--end::Thead-->
                    <!--begin::Tbody-->
                    <tbody>
                    <tr>
                      <td>
                        <label class="m-checkbox m-checkbox--solid m-checkbox--single m-checkbox--brand">
                          <input type="checkbox">
                          <span></span>
                        </label>
                      </td>
                      <td>
          																		<span class="m-widget11__title">
          																			Loop
          																		</span>
                        <span class="m-widget11__sub">
          																			CRM System
          																		</span>
                      </td>
                      <td>
                        19,200
                      </td>
                      <td>
                        <div class="m-widget11__chart" style="height:50px; width: 100px">
                          <iframe class="chartjs-hidden-iframe" tabindex="-1" style="display: block; overflow: hidden; border: 0px; margin: 0px; top: 0px; left: 0px; bottom: 0px; right: 0px; height: 100%; width: 100%; position: absolute; pointer-events: none; z-index: -1;"></iframe>
                          <canvas id="m_chart_sales_by_apps_2_1" style="display: block; width: 0px; height: 0px;" height="0" width="0"></canvas>
                        </div>
                      </td>
                      <td>
                        $63
                      </td>
                      <td class="m--align-right m--font-brand">
                        $34,740
                      </td>
                    </tr>
                    <tr>
                      <td>
                        <label class="m-checkbox m-checkbox--solid m-checkbox--single m-checkbox--brand">
                          <input type="checkbox">
                          <span></span>
                        </label>
                      </td>
                      <td>
          																		<span class="m-widget11__title">
          																			Selto
          																		</span>
                        <span class="m-widget11__sub">
          																			Powerful Website Builder
          																		</span>
                      </td>
                      <td>
                        24,310
                      </td>
                      <td>
                        <div class="m-widget11__chart" style="height:50px; width: 100px">
                          <iframe class="chartjs-hidden-iframe" tabindex="-1" style="display: block; overflow: hidden; border: 0px; margin: 0px; top: 0px; left: 0px; bottom: 0px; right: 0px; height: 100%; width: 100%; position: absolute; pointer-events: none; z-index: -1;"></iframe>
                          <canvas id="m_chart_sales_by_apps_2_2" style="display: block; width: 0px; height: 0px;" height="0" width="0"></canvas>
                        </div>
                      </td>
                      <td>
                        $39
                      </td>
                      <td class="m--align-right m--font-brand">
                        $46,010
                      </td>
                    </tr>
                    <tr>
                      <td>
                        <label class="m-checkbox m-checkbox--solid m-checkbox--single m-checkbox--brand">
                          <input type="checkbox">
                          <span></span>
                        </label>
                      </td>
                      <td>
          																		<span class="m-widget11__title">
          																			Jippo
          																		</span>
                        <span class="m-widget11__sub">
          																			The Best Selling App
          																		</span>
                      </td>
                      <td>
                        9,076
                      </td>
                      <td>
                        <div class="m-widget11__chart" style="height:50px; width: 100px">
                          <iframe class="chartjs-hidden-iframe" tabindex="-1" style="display: block; overflow: hidden; border: 0px; margin: 0px; top: 0px; left: 0px; bottom: 0px; right: 0px; height: 100%; width: 100%; position: absolute; pointer-events: none; z-index: -1;"></iframe>
                          <canvas id="m_chart_sales_by_apps_2_3" style="display: block; width: 0px; height: 0px;" height="0" width="0"></canvas>
                        </div>
                      </td>
                      <td>
                        $105
                      </td>
                      <td class="m--align-right m--font-brand">
                        $67,800
                      </td>
                    </tr>
                    <tr>
                      <td>
                        <label class="m-checkbox m-checkbox--solid m-checkbox--single m-checkbox--brand">
                          <input type="checkbox">
                          <span></span>
                        </label>
                      </td>
                      <td>
          																		<span class="m-widget11__title">
          																			Verto
          																		</span>
                        <span class="m-widget11__sub">
          																			Web Development Tool
          																		</span>
                      </td>
                      <td>
                        11,094
                      </td>
                      <td>
                        <div class="m-widget11__chart" style="height:50px; width: 100px">
                          <iframe class="chartjs-hidden-iframe" tabindex="-1" style="display: block; overflow: hidden; border: 0px; margin: 0px; top: 0px; left: 0px; bottom: 0px; right: 0px; height: 100%; width: 100%; position: absolute; pointer-events: none; z-index: -1;"></iframe>
                          <canvas id="m_chart_sales_by_apps_2_4" style="display: block; width: 0px; height: 0px;" height="0" width="0"></canvas>
                        </div>
                      </td>
                      <td>
                        $16
                      </td>
                      <td class="m--align-right m--font-brand">
                        $18,520
                      </td>
                    </tr>
                    </tbody>
                    <!--end::Tbody-->
                  </table>
                  <!--end::Table-->
                </div>
                <div class="m-widget11__action m--align-right">
                  <button type="button" class="btn m-btn--pill btn-secondary m-btn m-btn--custom m-btn--hover-brand">
                    Generate Report
                  </button>
                </div>
              </div>
              <!--end::Widget 11-->
            </div>
          </div>
        </div>
      </div>
      <!--end:: Widgets/Application Sales-->
    </div>
  </div>
</div>