config/routes.rb
Rails.application.routes.draw do

  root 'welcome#dashboard'
  resources :members
  devise_for :admins
  #devise_for :users
  resources :users
  resources :customers
  resources :orders
  resources :products
  resources :creditors
  resources :tokens, :only => [:create]
  put '/creditors/:id/paid' => 'creditors#paid_credits', :as => 'paid_credits'
  put '/orders/:id/paid' => 'orders#paid_company', :as => 'paid_company'
  put '/orders/:id/return' => 'orders#company_return', :as => 'company_return'
  get '/orders/admin-edit/:id' => 'orders#admin_edit', :as => 'admin_edit'
  get '/order/new/' => 'orders#admin_new', :as => 'admin_new'
  get '/notify' => 'welcome#notify', :as => 'notify'
  get '/test' => 'welcome#test', :as => 'test'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'orders/add_order'

end

app/views/layouts/_nav.html.erb

<ul class="m-menu__subnav">
  <% unless current_page?(new_order_path) %>
  <li class="m-menu__item  m-menu__item--submenu m-menu__item--rel m-menu__item--submenu-tabs"  data-menu-submenu-toggle="click" aria-haspopup="true">
    <a  href="#" class="m-menu__link m-menu__toggle">
      <i class="m-menu__link-icon flaticon-add"></i>
      <span class="m-menu__link-text">
																HR
															</span>
      <i class="m-menu__hor-arrow la la-angle-down"></i>
      <i class="m-menu__ver-arrow la la-angle-right"></i>
    </a>
    <div class="m-menu__submenu m-menu__submenu--classic m-menu__submenu--left">
      <span class="m-menu__arrow m-menu__arrow--adjust"></span>
      <ul class="m-menu__subnav">

        <li class="m-menu__item "  data-redirect="true" aria-haspopup="true">
          <a  href="/users/new" class="m-menu__link ">
            <i class="m-menu__link-icon flaticon-users"></i>
            <span class="m-menu__link-text">
																			Register Member
																		</span>
          </a>
        </li>
        <li class="m-menu__item "  data-redirect="true" aria-haspopup="true">
          <a  href="/members" class="m-menu__link ">
            <i class="m-menu__link-icon flaticon-users"></i>
            <span class="m-menu__link-text">
																			All Members
																		</span>
          </a>
        </li>
      </ul>
    </div>
  </li>
  <li class="m-menu__item  m-menu__item--submenu m-menu__item--rel m-menu__item--submenu-tabs"  data-menu-submenu-toggle="click" aria-haspopup="true">
    <a  href="#" class="m-menu__link m-menu__toggle">
      <i class="m-menu__link-icon flaticon-add"></i>
      <span class="m-menu__link-text">
																Creditors
															</span>
      <i class="m-menu__hor-arrow la la-angle-down"></i>
      <i class="m-menu__ver-arrow la la-angle-right"></i>
    </a>
    <div class="m-menu__submenu m-menu__submenu--classic m-menu__submenu--left">
      <span class="m-menu__arrow m-menu__arrow--adjust"></span>
      <ul class="m-menu__subnav">

        <li class="m-menu__item "  data-redirect="true" aria-haspopup="true">
          <a  href="/creditors" class="m-menu__link ">
            <i class="m-menu__link-icon flaticon-users"></i>
            <span class="m-menu__link-text">
																			All Creditors
																		</span>
          </a>
        </li>


      </ul>
    </div>
  </li>
  <li class="m-menu__item  m-menu__item--submenu m-menu__item--rel m-menu__item--submenu-tabs"  data-menu-submenu-toggle="click" aria-haspopup="true">
    <a  href="#" class="m-menu__link m-menu__toggle">
      <i class="m-menu__link-icon flaticon-add"></i>
      <span class="m-menu__link-text">
																Orders
															</span>
      <i class="m-menu__hor-arrow la la-angle-down"></i>
      <i class="m-menu__ver-arrow la la-angle-right"></i>
    </a>
    <div class="m-menu__submenu m-menu__submenu--classic m-menu__submenu--left">
      <span class="m-menu__arrow m-menu__arrow--adjust"></span>
      <ul class="m-menu__subnav">

        <li class="m-menu__item "  data-redirect="true" aria-haspopup="true">
          <a  href="/orders" class="m-menu__link ">
            <i class="m-menu__link-icon flaticon-users"></i>
            <span class="m-menu__link-text">
																			All Orders
																		</span>
          </a>
        </li>


      </ul>
    </div>
  </li>
  <% end %>
  <li class="m-menu__item  m-menu__item--submenu m-menu__item--rel m-menu__item--submenu-tabs"  data-menu-submenu-toggle="click" aria-haspopup="true">
    <a  href="/admins/sign_out" class="m-menu__link">
      <i class="m-menu__link-icon"></i>
      <span class="m-menu__link-text">
																Sign Out
															</span>

    </a>

  </li>
  <% unless current_page?(new_order_path) %>
  <li class="m-menu__item  m-menu__item--actions"  aria-haspopup="true">
    <div class="m-menu__link m-menu__link--toggle-skip">
      <a href="/order/new" class="btn btn-accent m-btn m-btn--icon m-btn--pill">
																<span>
																	<i class="la la-plus"></i>
																	<span>
																		New order
																	</span>
																</span>
      </a>
    </div>
  </li>
</ul>
<% end %>