config/routes.rb
Rails.application.routes.draw do

  root 'welcome#dashboard'
  resources :members
  devise_for :admins
  #devise_for :users
  resources :users
  resources :customers
  resources :orders
  resources :products
  resources :creditors
  resources :tokens, :only => [:create]
  put '/creditors/:id/paid' => 'creditors#paid_credits', :as => 'paid_credits'
  put '/orders/:id/paid' => 'orders#paid_company', :as => 'paid_company'
  put '/orders/:id/return' => 'orders#company_return', :as => 'company_return'
  get '/orders/admin-edit/:id' => 'orders#admin_edit', :as => 'admin_edit'
  get '/order/new/' => 'orders#admin_new', :as => 'admin_new'
  get '/notify' => 'welcome#notify', :as => 'notify'
  get '/test' => 'welcome#test', :as => 'test'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'orders/add_order'

end

app/models/member.rb
class Member < ApplicationRecord
  has_many :orders
  has_one :admin
  validates :name, :email, :time_rate, :day_rate, :night_rate, :time_cost, :day_cost, :night_cost, :fixed_rate, presence: true
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  # layout false
  # GET /members
  def index
    @page_title = 'All Members'

    @users = Member.all
  end

  # GET /members/1
  def show
    @page_title = 'Show'
    @orders = @member.orders.order(starttime: :desc)
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
    @page_title = 'Edit'
  end

  # POST /members
  def create
    @member = Member.new(member_params)

    if @member.save
      Admin.create(email: @member.email, password: "11111111", user_type: "members", member_id: @member.id)
      redirect_to members_path, notice: 'Member was successfully created.'
    else
      redirect_to new_user_path, notice: 'Form must be completed.'
    end
  end

  # PATCH/PUT /members/1
  def update
    if @member.update(member_params)
      unless @member.password.nil?
        @member.admin.update(password: @member.password)
      end
      redirect_to @member, notice: 'Member was successfully updated.'
    else
      render :edit
    end
  end
  

  # DELETE /members/1
  def destroy
    @member.destroy
    redirect_to members_url, notice: 'Member was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def member_params
      params.require(:member).permit(:name, :email, :job_rate, :time_rate, :day_rate, :night_rate, :time_cost, :day_cost, :night_cost, :fixed_rate, :hotel_fixed_cost, :normal_fixed_cost, :password)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :member_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :member_email %>
  </div>

  <div class="field">
    <%= form.label :job_rate %>
    <%= form.number_field :job_rate, id: :member_job_rate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb


<% content_for :breadcrumb do %>
    <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
      <li class="m-nav__item m-nav__item--home">
        <a href="#" class="m-nav__link m-nav__link--icon">
          <i class="m-nav__link-icon la la-home"></i>
        </a>
      </li>
      <li class="m-nav__separator">
        -
      </li>
      <li class="m-nav__item">
        <a href="/" class="m-nav__link">
											<span class="m-nav__link-text">
												Dashboard
											</span>
        </a>
      </li>
      <li class="m-nav__separator">
        -
      </li>
      <li class="m-nav__item">
        <a href="" class="m-nav__link">
											<span class="m-nav__link-text">
												Members
											</span>
        </a>
      </li>

    </ul>
<% end %>

<% content_for :scripts do %>
    <script type="text/javascript" charset="utf-8">
        $(document).ready(function(){
            $('#payment-type').on('change', function() {
                if ( this.value == 'Credit')
                {
                    $("#business").show();
                }
                else
                {
                    $("#business").hide();
                }
            });


        });
    </script>
<% end %>

<div class="m-content">
  <div class="row">
    <div class="col-lg-12">
      <!--begin::Portlet-->
      <div class="m-portlet">
        <div class="m-portlet__head">
          <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
          												<span class="m-portlet__head-icon m--hide">
          													<i class="la la-gear"></i>
          												</span>
              <h3 class="m-portlet__head-text">
                User Form
              </h3>
            </div>
          </div>
        </div>

        <%= form_for(@member, html: {class: "m-form"}) do |form| %>
            <div class="m-portlet__body">
              <div class="m-form__section m-form__section--first">
                <div class="form-group m-form__group">
                  <label for="example_input_full_name">
                    User Nick Name:
                  </label>
                  <%= form.text_field :name, id: :member_name, class: "form-control m-input", placeholder: "Enter full name" %>
                  <span class="m-form__help">
          														Please enter user's nick name
          													</span>
                </div>
                <div class="form-group m-form__group">
                  <label>
                    Email address:
                  </label>
                  <%= form.text_field :email, id: :member_email, class: "form-control m-input", placeholder: "Enter email" %>

                  <span class="m-form__help">
          														We'll never share your email with anyone else
          													</span>
                </div>
                <div class="form-group m-form__group">
                  <label>
                    Password:
                  </label>
                  <%= form.text_field :password, id: :member_email, class: "form-control m-input", placeholder: "Enter password" %>

                  <span class="m-form__help">
          														We'll never share your email with anyone else
          													</span>
                </div>
                <div class="form-group m-form__group">
                  <label>
                    Fixed rate
                  </label>
                  <div class="input-group">
                    <div class="input-group-prepend">
          															<span class="input-group-text" id="basic-addon2">
          																$
          															</span>
                    </div>
                    <%= form.number_field :fixed_rate, id: :member_job_rate, class: "form-control m-input"  %>

                  </div>
                </div>
                <div class="form-group m-form__group">
                  <label>
                    Time rate (per hour)
                  </label>
                  <div class="input-group">
                    <div class="input-group-prepend">
          															<span class="input-group-text" id="basic-addon2">
          																$
          															</span>
                    </div>
                    <%= form.number_field :time_rate, id: :member_job_rate, class: "form-control m-input"  %>

                  </div>
                </div>
                <div class="form-group m-form__group">
                  <label>
                    Day rate
                  </label>
                  <div class="input-group">
                    <div class="input-group-prepend">
          															<span class="input-group-text" id="basic-addon2">
          																$
          															</span>
                    </div>
                    <%= form.number_field :day_rate, id: :member_job_rate, class: "form-control m-input"  %>

                  </div>
                </div>
                <div class="form-group m-form__group">
                  <label>
                    Night rate
                  </label>
                  <div class="input-group">
                    <div class="input-group-prepend">
          															<span class="input-group-text" id="basic-addon2">
          																$
          															</span>
                    </div>
                    <%= form.number_field :night_rate, id: :member_job_rate, class: "form-control m-input"  %>

                  </div>
                </div>
                <div class="form-group m-form__group">
                  <label>
                    Hotel Fixed cost
                  </label>
                  <div class="input-group">
                    <div class="input-group-prepend">
          															<span class="input-group-text" id="basic-addon2">
          																$
          															</span>
                    </div>
                    <%= form.number_field :hotel_fixed_cost, id: :member_job_rate, class: "form-control m-input"  %>

                  </div>
                </div>
                <div class="form-group m-form__group">
                  <label>
                    Normal Fixed cost
                  </label>
                  <div class="input-group">
                    <div class="input-group-prepend">
          															<span class="input-group-text" id="basic-addon2">
          																$
          															</span>
                    </div>
                    <%= form.number_field :normal_fixed_cost, id: :member_job_rate, class: "form-control m-input"  %>

                  </div>
                </div>

                <div class="form-group m-form__group">
                  <label>
                    Time Cost (per hour)
                  </label>
                  <div class="input-group">
                    <div class="input-group-prepend">
          															<span class="input-group-text" id="basic-addon2">
          																$
          															</span>
                    </div>
                    <%= form.number_field :time_cost, id: :member_job_rate, class: "form-control m-input"  %>

                  </div>
                </div>
                <div class="form-group m-form__group">
                  <label>
                    Day Cost
                  </label>
                  <div class="input-group">
                    <div class="input-group-prepend">
          															<span class="input-group-text" id="basic-addon2">
          																$
          															</span>
                    </div>
                    <%= form.number_field :day_cost, id: :member_job_rate, class: "form-control m-input"  %>

                  </div>
                </div>
                <div class="form-group m-form__group">
                  <label>
                    Night Cost
                  </label>
                  <div class="input-group">
                    <div class="input-group-prepend">
          															<span class="input-group-text" id="basic-addon2">
          																$
          															</span>
                    </div>
                    <%= form.number_field :night_cost, id: :member_job_rate, class: "form-control m-input"  %>

                  </div>
                </div>
              </div>
            </div>
            <div class="m-portlet__foot m-portlet__foot--fit">
              <div class="m-form__actions m-form__actions">
                <%= form.submit "Update", class: "btn btn-primary" %>
                <%= link_to "Cancel", :back, class: "btn btn-secondary" %>
              </div>
            </div>
        <% end %>
        <!--end::Form-->
      </div>
      <!--end::Portlet-->

    </div>

  </div>
</div>

app/views/members/index.html.erb


<% content_for :breadcrumb do %>
    <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
      <li class="m-nav__item m-nav__item--home">
        <a href="#" class="m-nav__link m-nav__link--icon">
          <i class="m-nav__link-icon la la-home"></i>
        </a>
      </li>
      <li class="m-nav__separator">
        -
      </li>
      <li class="m-nav__item">
        <a href="/" class="m-nav__link">
											<span class="m-nav__link-text">
												Dashboard
											</span>
        </a>
      </li>
      <li class="m-nav__separator">
        -
      </li>
      <li class="m-nav__item">
        <a href="" class="m-nav__link">
											<span class="m-nav__link-text">
												Members
											</span>
        </a>
      </li>

    </ul>
<% end %>

<div class="m-content">
  <div class="row">
    <div class="col-xl-12">
      <!--begin:: Widgets/Application Sales-->
      <div class="m-portlet m-portlet--full-height  m-portlet--rounded">
        <div class="m-portlet__head">
          <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
              <h3 class="m-portlet__head-text">
                All Members
              </h3>
            </div>
          </div>
        </div>
        <div class="m-portlet__body">
          <div class="tab-content">
            <div class="tab-pane active" id="m_widget11_tab1_content">
              <!--begin::Widget 11-->
              <div class="m-widget11">
                <div class="table-responsive">
                  <!--begin::Table-->
                  <table class="table">
                    <!--begin::Thead-->
                    <thead>
                    <tr>
                      <td class="m-widget11__label">
                        #ID
                      </td>
                      <td class="m-widget11__app">
                        User Name
                      </td>
                      <td class="m-widget11__change">
                        Orders Completed
                      </td>
                      <td class="m-widget11__change">
                        Costs
                      </td>
                      <td class="m-widget11__price">
                        Working Days
                      </td>
                      <td class="m-widget11__total m--align-right">
                        Total
                      </td>
                      <td class="m-widget11__total m--align-right">

                      </td>
                    </tr>
                    </thead>
                    <!--end::Thead-->
                    <!--begin::Tbody-->
                    <tbody>
                    <tr>
                      <% @users.each do |user| %>
                          <td>

                          </td>
                          <td>
          																		<span class="m-widget11__title">
          																			<%= user.name %>
          																		</span>
                          </td>
                          <td>
                            <%= user.orders.count %>
                          </td>
                          <td>
                            <%= user.job_rate %>
                          </td>
                          <td>
                            <%= ((DateTime.now.to_time - user.created_at.to_time) / 1.day).floor %>
                          </td>
                          <td class="m--align-right m--font-brand">
                            <% if Order.where(member_id: user).exists? %>
                                $<%= Order.where(member_id: user).pluck(:amount).inject(0){|sum,x| sum + x } %>
                            <% else %>
                                $0
                            <% end %>
                          </td>

                          <td class="m--align-right m--font-brand">
                            <%= link_to "Edit", edit_member_path(user.id) %>
                          </td>
                          </tr>
                      <% end %>
                      </tbody>
                    <!--end::Tbody-->
                  </table>
                  <!--end::Table-->
                </div>
                <div class="m-widget11__action m--align-right">
                  <button type="button" class="btn m-btn--pill btn-secondary m-btn m-btn--custom m-btn--hover-brand">
                    Generate Report
                  </button>
                </div>
              </div>
              <!--end::Widget 11-->
            </div>
          </div>
        </div>
      </div>
      <!--end:: Widgets/Application Sales-->
    </div>
  </div>
</div>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb


<% content_for :breadcrumb do %>
    <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
      <li class="m-nav__item m-nav__item--home">
        <a href="#" class="m-nav__link m-nav__link--icon">
          <i class="m-nav__link-icon la la-home"></i>
        </a>
      </li>
      <li class="m-nav__separator">
        -
      </li>
      <li class="m-nav__item">
        <a href="/" class="m-nav__link">
											<span class="m-nav__link-text">
												Dashboard
											</span>
        </a>
      </li>
      <li class="m-nav__separator">
        -
      </li>
      <li class="m-nav__item">
        <a href="" class="m-nav__link">
											<span class="m-nav__link-text">
												Members
											</span>
        </a>
      </li>

    </ul>
<% end %>

<div class="m-content">
	<div class="row">
		<div class="col-xl-3 col-lg-4">
			<div class="m-portlet m-portlet--full-height   m-portlet--rounded">
				<div class="m-portlet__body">
					<div class="m-card-profile">
						<div class="m-card-profile__title m--hide">
							Your Profile
						</div>
						<div class="m-card-profile__pic">
							<div class="m-card-profile__pic-wrapper">
								<img src="/assets/demo/demo10/media/img/logo/logo2.png" alt=""/>
							</div>
						</div>
						<div class="m-card-profile__details">
							<span class="m-card-profile__name">
                <%= @member.name %>
              </span>
              <p>X-editable Bootstrap 3 popup</p>
              <div style="margin: 150px">
                  <a href="#" id="status" data-value="2"></a>
              </div>
							<a href="" class="m-card-profile__email m-link">
								<%= @member.email %>
							</a>
						</div>
					</div>
					<div class="m-portlet__body-separator"></div>
					<div class="m-widget1 m-widget1--paddingless">
						<div class="m-widget1__item">
							<div class="row m-row--no-padding align-items-center">
								<div class="col">
									<h3 class="m-widget1__title">
										Member Profit
									</h3>
								</div>
								<div class="col m--align-right">
									<span class="m-widget1__number m--font-brand">
										$<%= @member.orders.sum(:cost) %>
									</span>
								</div>
							</div>
						</div>
						<div class="m-widget1__item">
							<div class="row m-row--no-padding align-items-center">
								<div class="col">
									<h3 class="m-widget1__title">
										Total Profit
									</h3>
								</div>
								<div class="col m--align-right">
									<span class="m-widget1__number m--font-brand">
										$<%= @member.orders.sum(:amount) %>
									</span>
								</div>
							</div>
						</div>
						<div class="m-widget1__item">
							<div class="row m-row--no-padding align-items-center">
								<div class="col">
									<h3 class="m-widget1__title">
										Amount Paid (To Company)
									</h3>
								</div>
								<div class="col m--align-right">
									<span class="m-widget1__number m--font-brand">
										$<%= @member.orders.where(to_company: "Paid").sum(:amount) -   @member.orders.where(to_company: "Paid").sum(:cost) %>
									</span>
								</div>
							</div>
						</div>
						<div class="m-widget1__item">
							<div class="row m-row--no-padding align-items-center">
								<div class="col">
									<h3 class="m-widget1__title">
										Amount Yet To Paid
									</h3>
								</div>
								<div class="col m--align-right">
									<span class="m-widget1__number m--font-brand">
										$<%= (@member.orders.sum(:amount) - @member.orders.sum(:cost)) - (@member.orders.where(to_company: "Paid").sum(:amount) -   @member.orders.where(to_company: "Paid").sum(:cost)) %>
									</span>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-xl-9 col-lg-8">
      <div class="m-portlet">
        <div class="m-portlet__head">
          <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
          												<span class="m-portlet__head-icon m--hide">
          													<i class="la la-gear"></i>
          												</span>
              <h3 class="m-portlet__head-text">
                User Form
              </h3>
            </div>
          </div>
        </div>

            <div class="m-portlet__body">
              <div class="m-form__section m-form__section--first">
                <div class="form-group m-form__group">
                  <label for="example_input_full_name">
                    User Nick Name:
                  </label>
                  <p>
                    <%= @member.name %>
                  </p>
                
                </div>
                <div class="form-group m-form__group">
                  <label>
                    Email address:
                  </label>
                  <p>
                    <%= @member.email %>
                  </p>
                  
                  
                </div>
                <div class="form-group m-form__group">
                  <label>
                    Fixed rate
                  </label>

                    <p>
                      $<%= @member.fixed_rate %>
                    </p>
                    
                </div>
                <div class="form-group m-form__group">
                  <label>
                    Time rate (per hour)
                  </label>

                    <p>
                      $<%= @member.time_rate %>
                    </p>
                    

                </div>
                <div class="form-group m-form__group">
                  <label>
                    Day rate
                  </label>
                    <p>
                      $<%= @member.day_rate %>
                    </p>
                    

                </div>
                <div class="form-group m-form__group">
                  <label>
                    Night rate
                  </label>

                    <p>
                      $<%= @member.night_rate %>
                    </p>
                    
                </div>

                <div class="form-group m-form__group">
                  <label>
                    Hotel Fixed cost
                  </label>

                    <p>
                      $<%= @member.hotel_fixed_cost %>
                    </p>
                    
                </div>
                <div class="form-group m-form__group">
                  <label>
                    Normal Fixed cost
                  </label>

                    <p>
                      $<%= @member.normal_fixed_cost %>
                    </p>
                   
                </div>

                <div class="form-group m-form__group">
                  <label>
                    Time Cost (per hour)
                  </label>

                    <p>
                      $<%= @member.time_cost %>
                    </p>
                   
                </div>
                <div class="form-group m-form__group">
                  <label>
                    Day Cost
                  </label>

                    <p>
                      $<%= @member.day_cost %>
                    </p>
                  
                </div>
                <div class="form-group m-form__group">
                  <label>
                    Night Cost
                  </label>

                    <p>
                      $<%= @member.night_cost %>
                    </p>
                   
                </div>
              </div>
            </div>
            <div class="m-portlet__foot m-portlet__foot--fit">
              <div class="m-form__actions m-form__actions" style="padding: 10px;">
                <%= link_to "Edit", edit_member_path, class: "btn btn-primary" %>
                <%= link_to "Cancel", :back, class: "btn btn-secondary" %>
              </div>
            </div>
        <!--end::Form-->
      </div>
		</div>
	</div>
<div class="row">
  <div class="col-xl-12">
    <!--begin:: Widgets/Application Sales-->
    <div class="m-portlet m-portlet--full-height  m-portlet--rounded">
      <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
          <div class="m-portlet__head-title">
            <h3 class="m-portlet__head-text">
              All Members
            </h3>
          </div>
        </div>
      </div>
      <div class="m-portlet__body">
        <div class="tab-content">
          <div class="tab-pane active" id="m_widget11_tab1_content">
            <!--begin::Widget 11-->
            <div class="m-widget11">
              <div class="table-responsive">
                <!--begin::Table-->
                <table class="table" id="table-inline">
                  <!--begin::Thead-->
                  <thead>
                  <tr>
                    <td>
                      ID
                    </td>
                    <td>
                      Job Type
                    </td>
                    <td>
                      Time Start
                    </td>
                    <td>
                      Cost
                    </td>
                    <td>
                      Amount
                    </td>
                    
                    <td>
                      Status
                    </td>
                    <td>
                      Creditor Name
                    </td>
                    <td>
                      Amount To Company
                    </td>
                    <td>
                      Amount Paid
                    </td>
                    <td>
                      Action
                    </td>
                    <td>
                    </td>

                  </tr>
                  </thead>
                  <!--end::Thead-->
                  <!--begin::Tbody-->
                  <tbody>
                    <% @orders.each do |order| %>
                  <tr>
                    
                        <td>
																			<%= order.id %>
                        </td>
                        <td>
													<%= order.job_type %>
                        </td>
                        <td>
                          <%= order.starttime.strftime('%m-%d-%y %H:%M') %>
                        </td>
                        <td>
                          <%= order.cost %>
                        </td>
                        <td>
                          <%= order.amount %>
                        </td>
                        <td>
                          <%= order.status %>
                        </td>
                        <td>
                          <%= order.creditor_name %>
                        </td>
                        <td>
                          <%= order.amount - order.cost %>
                        </td>
                        <td>
                          <% if order.to_company == "Paid" %>
                          <%= order.amount - order.cost %>
                          <% else %>
                          0
                          <% end %>
                        </td>
                    
                        <td>
                          <% unless order.to_company == "Paid" %>
                              <%= link_to 'Paid', paid_company_path(order.id), method: :put %>
                          <% else %>
                              <%= link_to 'Revoke', company_return_path(order.id), method: :put %>
                          <% end %>
                        </td>
                        <td class="m--align-right m--font-brand">
                          <div class="fa fa-trash-alt"></div>

                        </td>
                        <td>
                          <a href="/orders/admin-edit/<%= order.id %>?redirect=back" rel="nofollow" class="m-portlet__nav-link btn m-btn m-btn--hover m-btn--icon m-btn--icon-only m-btn--pill" title="Delete">
                              <i class="la la-edit"></i>
                          </a>
                          
                          <a href="/orders/<%= order.id %>?redirect=back" data-method="delete" rel="nofollow" data-confirm="Are you sure?" class="m-portlet__nav-link btn m-btn m-btn--hover-danger m-btn--icon m-btn--icon-only m-btn--pill" title="Delete">
                              <i class="la la-trash"></i>
                          </a>
                        </td>
                      
                        </tr>
                        <% end %>
                    </tbody>
                  <!--end::Tbody-->
                </table>
                <!--end::Table-->
              </div>
              
            </div>
            <!--end::Widget 11-->
          </div>
          
        </div>
      </div>
    </div>
    <!--end:: Widgets/Application Sales-->
    
  </div>
</div>
</div>